import Link from "next/link";
/* Next.js의 Metadata 타입을 가져옴 */
import type { Metadata } from "next";
import "./globals.css";
import {Gochi_Hand} from 'next/font/google';

const gochiHand = Gochi_Hand({
  weight: '400',
  subsets: ['latin'],
});

/* 검색 엔진 */
export const metadata: Metadata = {
  title: "Reci-pick",
  description: "Generated by create next app",
};

/* 불변의 리액트 노드를 불러옴 */
export default function RootLayout({
children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang = "en" className = {gochiHand.className}>
      <body>
          <div className = "navbar">
            <Link href = "/">
              Reci-pick
              <span className = "icon">👨🏻‍🍳</span>
            </Link>
            <div className = "bubble">
              <span>What's your pick?</span>
            </div>
            <Link href = "/pick" className = "pick">
              <span className = "pick-icon">📖</span>
              <span className = "pick-name">my pick</span>
            </Link>
          </div>
          {children} {/* page.js 들어가는 곳 */}
      </body>
    </html>
  );
}